version: '3.1'

services:
  api_gateway:
    container_name: api
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - auth
    
  auth:
    container_name: auth
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis

  mongo:
    container_name: mongo
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: satoru
      MONGO_INITDB_ROOT_PASSWORD: mongosatoru
      MONGO_INITDB_DATABASE: pez
    ports:
      - 27017:27017
    depends_on:
      - auth


  trucha:
    container_name: trucha
    build:
      context: ./trucha_service
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    depends_on:
      - mongo

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  salchipapa:
    container_name: salchipapa
    build: 
      context: ./salchipapa_service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - auth

  cerezas:
    container_name: cerezas
    build:
      context: ./cerezas_service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - auth